#!/usr/bin/env bash
# This script installs nginx on server

sudo apt-get update -y && sudo apt-get upgrade -y
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo ufw allow 'Nginx HTTP'
sed -i 's/.*listen\s*80.*/listen 80;/g' /etc/nginx/sites-available/default
sudo service nginx restart
