#!/usr/bin/env bash
# Installs Nginx and configure it to Listen on port 80.
# Displays "Hello World!" when visited
# Configures /redirect_me as a "301 Moved Permanently".
# has 404 page containing "Sorry Page not found".

sudo apt-get update
sudo apt-get install -y nginx

sudo mkdir /etc/nginx/html
sudo touch /etc/nginx/html/index.html
echo "Hello World!" | sudo tee /etc/nginx/html/index.html
sudo touch /etc/nginx/html/404.html
echo "Sorry page not found" | sudo tee /etc/nginx/html/404.html

printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /etc/nginx/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 https://www.google.com;
    }
    error_page 404 /404.html;
    location /404 {
      root /etc/nginx/html;
      internal;
    }
}" > /etc/nginx/sites-available/default

sudo service nginx restart
