#!/usr/bin/env bash
# This Installs HAProxy version 1.8 and
# Enables management via the init script.
# also Distributes requests using a round-robin algorithm.

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy

echo "ENABLED=1" | sudo tee /etc/default/haproxy
sudo mv /etc/haproxy/haproxy.cfg{,.original}
sudo touch /etc/haproxy/haproxy.cfg

printf %s "global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy
defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000
listen hbnb
    bind *:80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor
    server gc-494442-web-01-54.86.24.142  check
    server gc-494442-web-02-52.90.23.36 check
" | sudo tee /etc/haproxy/haproxy.cfg

sudo service haproxy start
