#!/usr/bin/env bash
# Script creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# with sigterm it displays I hate the kill command
# with sigint it Displays Y U no love me?!
# with sigquit it deletes and terminates itself

file="/var/run/myscript.pid"

if [ ! -e "$file" ]; then
  touch "$file"
fi

sleep 2 &

echo "$!" > "$file"

trap 'echo "I hate the kill command"; rm "$file"; exit' SIGTERM SIGQUIT
trap "echo Y U no love me?!" SIGINT

while true; do
  echo "To infinity and beyond"
  sleep 2
done
