#!/usr/bin/env bash
# Script creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# with sigterm it displays I hate the kill command
# with sigint it Displays Y U no love me?!
# with sigquit it deletes and terminates itself

file=/var/run/myscript.pid
echo $$ > "$file"

while true
do
	echo "To infinity and beyond"
	sleep 2

	trap 'rm $file; exit' SIGQUIT
	trap 'echo I hate the kill command; rm $file; exit' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
done
