#!/usr/bin/env bash
# This script displays; "To infinity and beyond" indefinetly
# it displays "I am invincible!!!" when receiving a SIGTERM(termination signal)

while true
do
	echo "To infinity and beyond"
	sleep 2

	trap 'echo "I am invincible!!!"' SIGTERM
done
